//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nox.Integration.Service {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nox.Integration.Service.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string IntegrationDefinitionMissing {
            get {
                return ResourceManager.GetString("IntegrationDefinitionMissing", resourceCulture);
            }
        }
        
        internal static string IntegrationsDefinitionMissing {
            get {
                return ResourceManager.GetString("IntegrationsDefinitionMissing", resourceCulture);
            }
        }
        
        internal static string SourceMissing {
            get {
                return ResourceManager.GetString("SourceMissing", resourceCulture);
            }
        }
        
        internal static string TargetMissing {
            get {
                return ResourceManager.GetString("TargetMissing", resourceCulture);
            }
        }
        
        internal static string DataConnectionMissing {
            get {
                return ResourceManager.GetString("DataConnectionMissing", resourceCulture);
            }
        }
        
        internal static string SourceContructionFailure {
            get {
                return ResourceManager.GetString("SourceContructionFailure", resourceCulture);
            }
        }
        
        internal static string TargetContructionFailure {
            get {
                return ResourceManager.GetString("TargetContructionFailure", resourceCulture);
            }
        }
        
        internal static string ExecutorExecutionError {
            get {
                return ResourceManager.GetString("ExecutorExecutionError", resourceCulture);
            }
        }
    }
}
