version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src" # Nox.Generator.sln
    # Check for updates at 7 AM UTC
    schedule:
      interval: "daily"
      time: "07:00"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "MediatR" #until upgrade to .Net 8
      - dependency-name: "Microsoft.Build.Framework" #until upgrade to .Net
      - dependency-name: "Microsoft.CodeAnalysis.CSharp.Workspaces" #until upgrade to .Net 8 / Requires Latest VS, we do not want this
      - dependency-name: "Microsoft.CodeAnalysis.CSharp" #until upgrade to .Net 8 / Requires Latest VS, we do not want this
      - dependency-name: "Microsoft.CSharp" #until upgrade to .Net 8 / Requires Latest VS, we do not want this
      - dependency-name: "Microsoft.CodeAnalysis.Workspaces.MSBuild" #until upgrade to .Net 8 / Requires Latest VS, we do not want this
      - dependency-name: "Microsoft.CodeAnalysis.CSharp.Workspaces" # this is making dependabot failed, check again when upgrading to .Net 8 
  