version: "3.3"

services:
  vault:
    container_name: hashi-vault
    image: hashicorp/vault:latest
    restart: always
    volumes:
      - /vault/data
      - /etc/vault/logs
    ports:
      - "8300:8300/tcp"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8300"
    cap_add:
      - IPC_LOCK
    entrypoint: "vault server -dev"
    networks:
      - vault-network
   
  org-vault-init:
    container_name: org-vault-init
    image: alpine/curl
    depends_on:
      - vault
    volumes:
      - ./init_org_vault.sh:/usr/local/bin/init_vault.sh
    command: ["sh", "-c", "/usr/local/bin/init_vault.sh"]
    networks:
      - vault-network
  
  sln-vault-init:
    container_name: sln-vault-init
    image: alpine/curl
    depends_on:
      - vault
    volumes:
      - ./init_sln_vault.sh:/usr/local/bin/init_vault.sh
    command: ["sh", "-c", "/usr/local/bin/init_vault.sh"]
    networks:
      - vault-network
      
networks:
  vault-network:      
