version: '3.7'

volumes:
  postgres: 
  
services:
  postgres:
    container_name: postgres_container
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: SampleCurrencyDb
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "Developer*123"
      PGDATA: ./data
    ports:
      - "54320:5432"
    volumes:
      - postgres:/var/lib/postgresql/data