#
# cryptocash.apiConfiguration.nox.yaml
#
# yaml-language-server: $schema=../../../../../schemas/apiConfiguration.json
#

apiRouteMappings:

  - $ref: ./apiRouteMappings/countryByName.ApiRouteMapping.nox.yaml
  - $ref: ./apiRouteMappings/countryByNameOdataFiltering.ApiRouteMapping.nox.yaml
  - $ref: ./apiRouteMappings/countryByNameOdataFiltering3Segments.ApiRouteMapping.nox.yaml
  - $ref: ./apiRouteMappings/putRefCountryToWorkplace3Segments.ApiRouteMapping.nox.yaml
        