#
# integration.application.nox.yaml
#
# yaml-language-server: $schema=../../../../schemas/application.json
#

integrations:
  - $ref: ./integrations/query-to-table.integration.nox.yaml
    
  - $ref: ./integrations/json-to-table.integration.nox.yaml
    
  - $ref: ./integrations/proc-to-table.integration.nox.yaml
