#
# cryptocash.apiConfiguration.nox.yaml
#
# yaml-language-server: $schema=../../../../../schemas/apiConfiguration.json
#

apiRoutePrefix: /api

apiGenerateRelatedEndpointsMaxDepth: 2

apiRouteMappings:

  - $ref: ./apiRouteMappings/countriesByName.apiRouteMapping.nox.yaml

        