using System;
using System.Collections.Generic;

namespace Nox.Types;

public static class CurrencySymbol
{
    private static Dictionary<CurrencyCode, string> CurrencySymbols = new ()
    {
        { CurrencyCode.AED, "د.إ" },
        { CurrencyCode.AFN, "؋" },
        { CurrencyCode.ALL, "L" },
        { CurrencyCode.AMD, "֏" },
        { CurrencyCode.ANG, "ƒ" },
        { CurrencyCode.AOA, "Kz" },
        { CurrencyCode.ARS, "$" },
        { CurrencyCode.AUD, "$" },
        { CurrencyCode.AWG, "ƒ" },
        { CurrencyCode.AZN, "₼" },
        { CurrencyCode.BAM, "KM" },
        { CurrencyCode.BBD, "$" },
        { CurrencyCode.BDT, "৳" },
        { CurrencyCode.BGN, "лв" },
        { CurrencyCode.BHD, ".د.ب" },
        { CurrencyCode.BIF, "Fr" },
        { CurrencyCode.BMD, "$" },
        { CurrencyCode.BND, "$" },
        { CurrencyCode.BOB, "Bs." },
        { CurrencyCode.BOV, "Mvdol" },
        { CurrencyCode.BRL, "R$" },
        { CurrencyCode.BSD, "$" },
        { CurrencyCode.BTN, "Nu." },
        { CurrencyCode.BWP, "P" },
        { CurrencyCode.BYN, "Br" },
        { CurrencyCode.BZD, "$" },
        { CurrencyCode.CAD, "$" },
        { CurrencyCode.CDF, "Fr" },
        { CurrencyCode.CHF, "Fr" },
        { CurrencyCode.CLF, "UF" },
        { CurrencyCode.CLP, "$" },
        { CurrencyCode.COP, "$" },
        { CurrencyCode.CRC, "₡" },
        { CurrencyCode.CUC, "$" },
        { CurrencyCode.CUP, "$" },
        { CurrencyCode.CVE, "$" },
        { CurrencyCode.CZK, "Kč" },
        { CurrencyCode.DJF, "Fdj" },
        { CurrencyCode.DKK, "kr" },
        { CurrencyCode.DOP, "$" },
        { CurrencyCode.DZD, "د.ج" },
        { CurrencyCode.EGP, "£" },
        { CurrencyCode.ERN, "Nfk" },
        { CurrencyCode.ETB, "Br" },
        { CurrencyCode.EUR, "€" },
        { CurrencyCode.FJD, "$" },
        { CurrencyCode.FKP, "£" },
        { CurrencyCode.GBP, "£" },
        { CurrencyCode.GEL, "₾" },
        { CurrencyCode.GHS, "₵" },
        { CurrencyCode.GIP, "£" },
        { CurrencyCode.GMD, "D" },
        { CurrencyCode.GNF, "Fr" },
        { CurrencyCode.GTQ, "Q" },
        { CurrencyCode.GYD, "$" },
        { CurrencyCode.HKD, "$" },
        { CurrencyCode.HNL, "L" },
        { CurrencyCode.HTG, "G" },
        { CurrencyCode.HUF, "Ft" },
        { CurrencyCode.IDR, "Rp" },
        { CurrencyCode.ILS, "₪" },
        { CurrencyCode.INR, "₹" },
        { CurrencyCode.IQD, "ع.د" },
        { CurrencyCode.IRR, "﷼" },
        { CurrencyCode.ISK, "kr" },
        { CurrencyCode.JMD, "$" },
        { CurrencyCode.JOD, "د.ا" },
        { CurrencyCode.JPY, "¥" },
        { CurrencyCode.KES, "Sh" },
        { CurrencyCode.KGS, "с" },
        { CurrencyCode.KHR, "៛" },
        { CurrencyCode.KMF, "Fr" },
        { CurrencyCode.KPW, "₩" },
        { CurrencyCode.KRW, "₩" },
        { CurrencyCode.KWD, "د.ك" },
        { CurrencyCode.KYD, "$" },
        { CurrencyCode.KZT, "₸" },
        { CurrencyCode.LAK, "₭" },
        { CurrencyCode.LBP, "ل.ل" },
        { CurrencyCode.LKR, "₨" },
        { CurrencyCode.LRD, "$" },
        { CurrencyCode.LSL, "L" },
        { CurrencyCode.LYD, "ل.د" },
        { CurrencyCode.MAD, "د.م." },
        { CurrencyCode.MDL, "L" },
        { CurrencyCode.MGA, "Ar" },
        { CurrencyCode.MKD, "ден" },
        { CurrencyCode.MMK, "Ks" },
        { CurrencyCode.MNT, "₮" },
        { CurrencyCode.MOP, "P" },
        { CurrencyCode.MRU, "UM" },
        { CurrencyCode.MUR, "₨" },
        { CurrencyCode.MVR, "ރ" },
        { CurrencyCode.MWK, "MK" },
        { CurrencyCode.MXN, "$" },
        { CurrencyCode.MYR, "RM" },
        { CurrencyCode.MZN, "MT" },
        { CurrencyCode.NAD, "$" },
        { CurrencyCode.NGN, "₦" },
        { CurrencyCode.NIO, "C$" },
        { CurrencyCode.NOK, "kr" },
        { CurrencyCode.NPR, "₨" },
        { CurrencyCode.NZD, "$" },
        { CurrencyCode.OMR, "ر.ع." },
        { CurrencyCode.PAB, "B/." },
        { CurrencyCode.PEN, "S/." },
        { CurrencyCode.PGK, "K" },
        { CurrencyCode.PHP, "₱" },
        { CurrencyCode.PKR, "₨" },
        { CurrencyCode.PLN, "zł" },
        { CurrencyCode.PYG, "₲" },
        { CurrencyCode.QAR, "ر.ق" },
        { CurrencyCode.RON, "lei" },
        { CurrencyCode.RSD, "дин" },
        { CurrencyCode.RUB, "₽" },
        { CurrencyCode.RWF, "Fr" },
        { CurrencyCode.SAR, "ر.س" },
        { CurrencyCode.SBD, "$" },
        { CurrencyCode.SCR, "₨" },
        { CurrencyCode.SDG, "ج.س." },
        { CurrencyCode.SEK, "kr" },
        { CurrencyCode.SGD, "$" },
        { CurrencyCode.SHP, "£" },
        { CurrencyCode.SLL, "Le" },
        { CurrencyCode.SOS, "Sh" },
        { CurrencyCode.SRD, "$" },
        { CurrencyCode.SSP, "£" },
        { CurrencyCode.STN, "Db" },
        { CurrencyCode.SYP, "£" },
        { CurrencyCode.SZL, "L" },
        { CurrencyCode.THB, "฿" },
        { CurrencyCode.TJS, "SM" },
        { CurrencyCode.TMT, "m" },
        { CurrencyCode.TND, "د.ت" },
        { CurrencyCode.TOP, "T$" },
        { CurrencyCode.TRY, "₺" },
        { CurrencyCode.TTD, "$" },
        { CurrencyCode.TWD, "$" },
        { CurrencyCode.TZS, "Sh" },
        { CurrencyCode.UAH, "₴" },
        { CurrencyCode.UGX, "Sh" },
        { CurrencyCode.USD, "$" },
        { CurrencyCode.UYU, "$U" },
        { CurrencyCode.UZS, "so'm" },
        { CurrencyCode.VES, "Bs." },
        { CurrencyCode.VND, "₫" },
        { CurrencyCode.VUV, "Vt" },
        { CurrencyCode.WST, "WS$" },
        { CurrencyCode.XAF, "Fr" },
        { CurrencyCode.XCD, "$" },
        { CurrencyCode.XOF, "Fr" },
        { CurrencyCode.XPF, "Fr" },
        { CurrencyCode.YER, "﷼" },
        { CurrencyCode.ZAR, "R" },
        { CurrencyCode.ZMW, "ZK" },
        { CurrencyCode.ZWL, "$" },
    };


    public static string GetCurrencySymbol(CurrencyCode currencyCode)
    {
        if (CurrencySymbols.TryGetValue(currencyCode, out var symbol))
        {
            return symbol;
        }

        throw new ArgumentOutOfRangeException(nameof(currencyCode), currencyCode, "Unknown currency code.");
    }
}