#
# employee.entity.nox.yaml
# 
# yaml-language-server: $schema=../../../../../schemas/entity.json
#

name: ApplicationIAM

description: ApplicationIAM

keys:

  - name: Id
    isRequired: true
    description: Application Id
    type: databaseNumber

attributes:

  - name: FirstName
    description: The employee's first name
    type: text
    textTypeOptions:
      minLength: 4
      maxLength: 63
    isRequired: true

  - name: LastName
    description: The employee's last name
    type: text
    textTypeOptions:
      minLength: 4
      maxLength: 63
    isRequired: true

  
persistence:
    isAudited: true    
    schema: dbo
    create:
        isEnabled: true
        raiseEvents: true
    read:
        isEnabled: true
    update:
        isEnabled: true
        raiseEvents: true
    delete:
        isEnabled: true
        raiseEvents: true
        useSoftDelete: true