//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nox.Ui.Blazor.Lib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nox.Ui.Blazor.Lib.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        public static string AddEntity {
            get {
                return ResourceManager.GetString("AddEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string EditEntity {
            get {
                return ResourceManager.GetString("EditEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude: {0}, Longitude: {1}.
        /// </summary>
        public static string LatLongSummary {
            get {
                return ResourceManager.GetString("LatLongSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results Found.
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string TitleAddressLine1 {
            get {
                return ResourceManager.GetString("TitleAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string TitleAddressLine2 {
            get {
                return ResourceManager.GetString("TitleAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Area 1.
        /// </summary>
        public static string TitleAdministrativeArea1 {
            get {
                return ResourceManager.GetString("TitleAdministrativeArea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Area 2.
        /// </summary>
        public static string TitleAdministrativeArea2 {
            get {
                return ResourceManager.GetString("TitleAdministrativeArea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryId.
        /// </summary>
        public static string TitleCountryId {
            get {
                return ResourceManager.GetString("TitleCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        public static string TitleCurrencyCode {
            get {
                return ResourceManager.GetString("TitleCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime Range.
        /// </summary>
        public static string TitleDateTimeRange {
            get {
                return ResourceManager.GetString("TitleDateTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Hour.
        /// </summary>
        public static string TitleEndHour {
            get {
                return ResourceManager.GetString("TitleEndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Millisecond.
        /// </summary>
        public static string TitleEndMillisecond {
            get {
                return ResourceManager.GetString("TitleEndMillisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Minute.
        /// </summary>
        public static string TitleEndMinute {
            get {
                return ResourceManager.GetString("TitleEndMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Second.
        /// </summary>
        public static string TitleEndSecond {
            get {
                return ResourceManager.GetString("TitleEndSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        public static string TitleLocality {
            get {
                return ResourceManager.GetString("TitleLocality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood.
        /// </summary>
        public static string TitleNeighborhood {
            get {
                return ResourceManager.GetString("TitleNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string TitlePostalCode {
            get {
                return ResourceManager.GetString("TitlePostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string TitleRoute {
            get {
                return ResourceManager.GetString("TitleRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Hour.
        /// </summary>
        public static string TitleStartHour {
            get {
                return ResourceManager.GetString("TitleStartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Millisecond.
        /// </summary>
        public static string TitleStartMillisecond {
            get {
                return ResourceManager.GetString("TitleStartMillisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minute.
        /// </summary>
        public static string TitleStartMinute {
            get {
                return ResourceManager.GetString("TitleStartMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Second.
        /// </summary>
        public static string TitleStartSecond {
            get {
                return ResourceManager.GetString("TitleStartSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string TitleStreetAddress {
            get {
                return ResourceManager.GetString("TitleStreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid {1}.
        /// </summary>
        public static string ValidateGeneric {
            get {
                return ResourceManager.GetString("ValidateGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required and must be at least {1} characters long.
        /// </summary>
        public static string ValidateTextLength {
            get {
                return ResourceManager.GetString("ValidateTextLength", resourceCulture);
            }
        }
    }
}
