#
# sql-country-source.dataConnection.nox.yaml
#
# yaml-language-server: $schema=../../../../../../schemas/dataConnection.json
#

name: SqlCountrySource
provider: sqlServer
options: Trusted_Connection=no;connection timeout=120;TrustServerCertificate=True;encrypt=false
serverUri: localhost
user: sa
password: Developer*123