using System.Reflection;
using Microsoft.CodeAnalysis;
using Nox.Generator.Common;
using Nox.Solution;
using Nox.Types;

namespace Nox.Generator.Application.EventGenerator;

public class ApplicationEventGenerator
{
    public static void Generate(SourceProductionContext context, NoxSolutionCodeGeneratorState codeGeneratorState)
    {
        context.CancellationToken.ThrowIfCancellationRequested();

        if (codeGeneratorState.Solution.Application?.Events == null) return;

        foreach (var evt in codeGeneratorState.Solution.Application.Events)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            GenerateEvent(context, codeGeneratorState, evt);
        }
    }

    private static void GenerateEvent(SourceProductionContext context, NoxSolutionCodeGeneratorState codeGeneratorState, ApplicationEvent evt)
    {
        var code = new CodeBuilder($"{evt.Name}.g.cs", context);

        code.AppendLine($"// Generated by {nameof(DtoGenerator)}::{MethodBase.GetCurrentMethod()!.Name}");
        code.AppendLine();
        //NOTE: this must point to the Nox abstractions
        code.AppendLine($"using Nox.Abstractions;");
        code.AppendLine($"using Nox.Types;");
        code.AppendLine($"using System.Collections.Generic;");
        code.AppendLine();
        code.AppendLine($"namespace {codeGeneratorState.Events};");

        GenerateClassDocs(context, code, evt);

        code.AppendLine($"public partial class {evt.Name} : INoxApplicationEvent");
        code.StartBlock();

        GenerateProperties(context, code, evt);

        code.EndBlock();
        
        code.GenerateSourceCode();
    }
    
    private static void GenerateClassDocs(SourceProductionContext context, CodeBuilder code, ApplicationEvent evt)
    {
        if (evt.Description is not null)
        {
            code.AppendLine();
            code.AppendLine($"/// <summary>");
            code.AppendLine($"/// {evt.Description.EnsureEndsWith('.')}");
            code.AppendLine($"/// </summary>");
        }
    }
    
    
    private static void GenerateProperties(SourceProductionContext context, CodeBuilder code, ApplicationEvent evt)
    {
        if (evt.ObjectTypeOptions != null)
        {
            foreach (var attribute in evt.ObjectTypeOptions.Attributes)
            {
                context.CancellationToken.ThrowIfCancellationRequested();
        
                GeneratePropertyDocs(context, code, attribute);
        
                var propType = attribute.Type;
                var propName = attribute.Name;
                var nullable = attribute.IsRequired ? string.Empty : "?";
        
                code.AppendLine($"public {propType}{nullable} {propName} {{ get; set; }} = null!;");
            }
        }
    }
    
    private static void GeneratePropertyDocs(SourceProductionContext context, CodeBuilder code, NoxSimpleTypeDefinition prop)
    {
        if (!string.IsNullOrWhiteSpace(prop.Description))
        {
            code.AppendLine();
            code.AppendLine($"/// <summary>");
            code.AppendLine($"/// {prop.Description!.TrimEnd('.')}.");
            code.AppendLine($"/// </summary>"); 
        }
    }
}