//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nox.Solution {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nox.Solution.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SolutionNameEmpty {
            get {
                return ResourceManager.GetString("SolutionNameEmpty", resourceCulture);
            }
        }
        
        internal static string EnvironmentNameEmpty {
            get {
                return ResourceManager.GetString("EnvironmentNameEmpty", resourceCulture);
            }
        }
        
        internal static string EnvironmentNameDuplicate {
            get {
                return ResourceManager.GetString("EnvironmentNameDuplicate", resourceCulture);
            }
        }
        
        internal static string VersionControlProviderEmpty {
            get {
                return ResourceManager.GetString("VersionControlProviderEmpty", resourceCulture);
            }
        }
        
        internal static string VersionControlHostEmpty {
            get {
                return ResourceManager.GetString("VersionControlHostEmpty", resourceCulture);
            }
        }
        
        internal static string VersionControlSourceFolderEmpty {
            get {
                return ResourceManager.GetString("VersionControlSourceFolderEmpty", resourceCulture);
            }
        }
        
        internal static string VersionControlContainersFolderEmpty {
            get {
                return ResourceManager.GetString("VersionControlContainersFolderEmpty", resourceCulture);
            }
        }
        
        internal static string TeamUserNameEmpty {
            get {
                return ResourceManager.GetString("TeamUserNameEmpty", resourceCulture);
            }
        }
        
        internal static string TeamRolesEmpty {
            get {
                return ResourceManager.GetString("TeamRolesEmpty", resourceCulture);
            }
        }
        
        internal static string DomainEntitiesEmpty {
            get {
                return ResourceManager.GetString("DomainEntitiesEmpty", resourceCulture);
            }
        }
        
        internal static string EntityNameEmpty {
            get {
                return ResourceManager.GetString("EntityNameEmpty", resourceCulture);
            }
        }
        
        internal static string EntityNameDuplicate {
            get {
                return ResourceManager.GetString("EntityNameDuplicate", resourceCulture);
            }
        }
        
        internal static string TeamUserNameDuplicate {
            get {
                return ResourceManager.GetString("TeamUserNameDuplicate", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipNameEmpty {
            get {
                return ResourceManager.GetString("EntityRelationshipNameEmpty", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipNameDuplicate {
            get {
                return ResourceManager.GetString("EntityRelationshipNameDuplicate", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipDescriptionEmpty {
            get {
                return ResourceManager.GetString("EntityRelationshipDescriptionEmpty", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipRelationshipEmpty {
            get {
                return ResourceManager.GetString("EntityRelationshipRelationshipEmpty", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipEntityEmpty {
            get {
                return ResourceManager.GetString("EntityRelationshipEntityEmpty", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipEntityMissing {
            get {
                return ResourceManager.GetString("EntityRelationshipEntityMissing", resourceCulture);
            }
        }
        
        internal static string EntityRelationshipCanNavigate {
            get {
                return ResourceManager.GetString("EntityRelationshipCanNavigate", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipNameEmpty {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipNameEmpty", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipNameDuplicate {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipNameDuplicate", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipDescriptionEmpty {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipDescriptionEmpty", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipRelationshipEmpty {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipRelationshipEmpty", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipEntityEmpty {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipEntityEmpty", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipEntityMissing {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipEntityMissing", resourceCulture);
            }
        }
        
        internal static string EntityOwnedRelationshipEntityUsedMultipleTimes {
            get {
                return ResourceManager.GetString("EntityOwnedRelationshipEntityUsedMultipleTimes", resourceCulture);
            }
        }
        
        internal static string DomainQueryNameEmpty {
            get {
                return ResourceManager.GetString("DomainQueryNameEmpty", resourceCulture);
            }
        }
        
        internal static string DomainQueryResponseOutputEmpty {
            get {
                return ResourceManager.GetString("DomainQueryResponseOutputEmpty", resourceCulture);
            }
        }
        
        internal static string DomainQueryRequestNameEmpty {
            get {
                return ResourceManager.GetString("DomainQueryRequestNameEmpty", resourceCulture);
            }
        }
        
        internal static string DomainQueryRequestTypeEmpty {
            get {
                return ResourceManager.GetString("DomainQueryRequestTypeEmpty", resourceCulture);
            }
        }
        
        internal static string DomainQueryNameDuplicate {
            get {
                return ResourceManager.GetString("DomainQueryNameDuplicate", resourceCulture);
            }
        }
        
        internal static string DomainQueryResponseNameEmpty {
            get {
                return ResourceManager.GetString("DomainQueryResponseNameEmpty", resourceCulture);
            }
        }
        
        internal static string DomainQueryResponseTypeEmpty {
            get {
                return ResourceManager.GetString("DomainQueryResponseTypeEmpty", resourceCulture);
            }
        }
        
        internal static string CollectionTypeOptionsNameEmpty {
            get {
                return ResourceManager.GetString("CollectionTypeOptionsNameEmpty", resourceCulture);
            }
        }
        
        internal static string CollectionTypeOptionsTypeEmpty {
            get {
                return ResourceManager.GetString("CollectionTypeOptionsTypeEmpty", resourceCulture);
            }
        }
        
        internal static string ObjectTypeOptionsAttributesEmpty {
            get {
                return ResourceManager.GetString("ObjectTypeOptionsAttributesEmpty", resourceCulture);
            }
        }
        
        internal static string DomainCommandNameEmpty {
            get {
                return ResourceManager.GetString("DomainCommandNameEmpty", resourceCulture);
            }
        }
        
        internal static string DomainCommandNameDuplicate {
            get {
                return ResourceManager.GetString("DomainCommandNameDuplicate", resourceCulture);
            }
        }
        
        internal static string DomainCommandTypeEmpty {
            get {
                return ResourceManager.GetString("DomainCommandTypeEmpty", resourceCulture);
            }
        }
        
        internal static string SimpleTypeNameEmpty {
            get {
                return ResourceManager.GetString("SimpleTypeNameEmpty", resourceCulture);
            }
        }
        
        internal static string SimpleTypeTypeEmpty {
            get {
                return ResourceManager.GetString("SimpleTypeTypeEmpty", resourceCulture);
            }
        }
        
        internal static string EntityAttributesEmpty {
            get {
                return ResourceManager.GetString("EntityAttributesEmpty", resourceCulture);
            }
        }
        
        internal static string DtoNameEmpty {
            get {
                return ResourceManager.GetString("DtoNameEmpty", resourceCulture);
            }
        }
        
        internal static string DtoAttributesEmpty {
            get {
                return ResourceManager.GetString("DtoAttributesEmpty", resourceCulture);
            }
        }
        
        internal static string DtoNameDuplicate {
            get {
                return ResourceManager.GetString("DtoNameDuplicate", resourceCulture);
            }
        }
        
        internal static string IntegrationNameEmpty {
            get {
                return ResourceManager.GetString("IntegrationNameEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationNameDuplicate {
            get {
                return ResourceManager.GetString("IntegrationNameDuplicate", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceMissing {
            get {
                return ResourceManager.GetString("IntegrationSourceMissing", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetMissing {
            get {
                return ResourceManager.GetString("IntegrationTargetMissing", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceNameEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceNameEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceDataConnectionEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceDataConnectionEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationScheduleStartEmpty {
            get {
                return ResourceManager.GetString("IntegrationScheduleStartEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceDataConnectionMissing {
            get {
                return ResourceManager.GetString("IntegrationSourceDataConnectionMissing", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetNameEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetNameEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetTypeEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetTypeEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetDataConnectionEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetDataConnectionEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetDataConnectionMissing {
            get {
                return ResourceManager.GetString("IntegrationTargetDataConnectionMissing", resourceCulture);
            }
        }
        
        internal static string IntegrationMappingSourceColumnMissing {
            get {
                return ResourceManager.GetString("IntegrationMappingSourceColumnMissing", resourceCulture);
            }
        }
        
        internal static string IntegrationMappingTargetAttributeMissing {
            get {
                return ResourceManager.GetString("IntegrationMappingTargetAttributeMissing", resourceCulture);
            }
        }
        
        internal static string IntegrationMatchTableEmpty {
            get {
                return ResourceManager.GetString("IntegrationMatchTableEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationMatchLookupColumnEmpty {
            get {
                return ResourceManager.GetString("IntegrationMatchLookupColumnEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationMatchReturnColumnEmpty {
            get {
                return ResourceManager.GetString("IntegrationMatchReturnColumnEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationLookupSourceColumnEmpty {
            get {
                return ResourceManager.GetString("IntegrationLookupSourceColumnEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationLookupMatchEmpty {
            get {
                return ResourceManager.GetString("IntegrationLookupMatchEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationLookupTargetAttributeEmpty {
            get {
                return ResourceManager.GetString("IntegrationLookupTargetAttributeEmpty", resourceCulture);
            }
        }
        
        internal static string ServerNameEmpty {
            get {
                return ResourceManager.GetString("ServerNameEmpty", resourceCulture);
            }
        }
        
        internal static string ServerNameDuplicate {
            get {
                return ResourceManager.GetString("ServerNameDuplicate", resourceCulture);
            }
        }
        
        internal static string PersistenceDatabaseServerEmpty {
            get {
                return ResourceManager.GetString("PersistenceDatabaseServerEmpty", resourceCulture);
            }
        }
        
        internal static string PersistenceDatabaseSqliteAutoNumberLimitation {
            get {
                return ResourceManager.GetString("PersistenceDatabaseSqliteAutoNumberLimitation", resourceCulture);
            }
        }
        
        internal static string SecretsValidForInvalidTimespan {
            get {
                return ResourceManager.GetString("SecretsValidForInvalidTimespan", resourceCulture);
            }
        }
        
        internal static string DataConnectionProviderEmpty {
            get {
                return ResourceManager.GetString("DataConnectionProviderEmpty", resourceCulture);
            }
        }
        
        internal static string EmailServerProviderEmpty {
            get {
                return ResourceManager.GetString("EmailServerProviderEmpty", resourceCulture);
            }
        }
        
        internal static string SmsServerProviderEmpty {
            get {
                return ResourceManager.GetString("SmsServerProviderEmpty", resourceCulture);
            }
        }
        
        internal static string ImServerProviderEmpty {
            get {
                return ResourceManager.GetString("ImServerProviderEmpty", resourceCulture);
            }
        }
        
        internal static string SecretsServerProviderEmpty {
            get {
                return ResourceManager.GetString("SecretsServerProviderEmpty", resourceCulture);
            }
        }
        
        internal static string EntityDefaultsFalse {
            get {
                return ResourceManager.GetString("EntityDefaultsFalse", resourceCulture);
            }
        }
        
        internal static string EntityPersistenceDefaultsFalse {
            get {
                return ResourceManager.GetString("EntityPersistenceDefaultsFalse", resourceCulture);
            }
        }
        
        internal static string EntityPersistenceTableNameEmpty {
            get {
                return ResourceManager.GetString("EntityPersistenceTableNameEmpty", resourceCulture);
            }
        }
        
        internal static string ServerUriEmpty {
            get {
                return ResourceManager.GetString("ServerUriEmpty", resourceCulture);
            }
        }
        
        internal static string ServerUriInvalid {
            get {
                return ResourceManager.GetString("ServerUriInvalid", resourceCulture);
            }
        }
        
        internal static string ServerUriInvalidScheme {
            get {
                return ResourceManager.GetString("ServerUriInvalidScheme", resourceCulture);
            }
        }
        
        internal static string IntegrationEventsServerDefaultsFalse {
            get {
                return ResourceManager.GetString("IntegrationEventsServerDefaultsFalse", resourceCulture);
            }
        }
        
        internal static string DatabaseServerProviderEmpty {
            get {
                return ResourceManager.GetString("DatabaseServerProviderEmpty", resourceCulture);
            }
        }
        
        internal static string EventSourceServerProviderEmpty {
            get {
                return ResourceManager.GetString("EventSourceServerProviderEmpty", resourceCulture);
            }
        }
        
        internal static string CacheServerProviderEmpty {
            get {
                return ResourceManager.GetString("CacheServerProviderEmpty", resourceCulture);
            }
        }
        
        internal static string SearchServerProviderEmpty {
            get {
                return ResourceManager.GetString("SearchServerProviderEmpty", resourceCulture);
            }
        }
        
        internal static string ApiServerProviderEmpty {
            get {
                return ResourceManager.GetString("ApiServerProviderEmpty", resourceCulture);
            }
        }
        
        internal static string BffServerProviderEmpty {
            get {
                return ResourceManager.GetString("BffServerProviderEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceDatabaseOptionsEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceDatabaseOptionsEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetDatabaseOptionsEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetDatabaseOptionsEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceDatabaseOptionsQueryEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceDatabaseOptionsQueryEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetDatabaseOptionsStoredProcEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetDatabaseOptionsStoredProcEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceDatabaseOptionsMinExptectedRecordsInvalid {
            get {
                return ResourceManager.GetString("IntegrationSourceDatabaseOptionsMinExptectedRecordsInvalid", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceFileOptionsEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceFileOptionsEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetFileOptionsEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetFileOptionsEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceMsgQueueOptionsEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceMsgQueueOptionsEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetMsgQueueOptionsEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetMsgQueueOptionsEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceHttpOptionsEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceHttpOptionsEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetHttpOptionsEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetHttpOptionsEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceFileOptionsFilenameEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceFileOptionsFilenameEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetFileAttributesEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetFileAttributesEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceFileAttributesEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceFileAttributesEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetMessageAttributesEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetMessageAttributesEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceMessageAttributesEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceMessageAttributesEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetHttpRequestAttributesEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetHttpRequestAttributesEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceHttpResponseAttributesEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceHttpResponseAttributesEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetFileOptionsFilenameEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetFileOptionsFilenameEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceFileOptionsMinExptectedRecordsInvalid {
            get {
                return ResourceManager.GetString("IntegrationSourceFileOptionsMinExptectedRecordsInvalid", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceHttpOptionsRouteEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceHttpOptionsRouteEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceHttpOptionsFormatEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceHttpOptionsFormatEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceHttpOptionsVerbEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceHttpOptionsVerbEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationSourceMsgQueueOptionsSourceEmpty {
            get {
                return ResourceManager.GetString("IntegrationSourceMsgQueueOptionsSourceEmpty", resourceCulture);
            }
        }
        
        internal static string DomainEventNameEmpty {
            get {
                return ResourceManager.GetString("DomainEventNameEmpty", resourceCulture);
            }
        }
        
        internal static string ApplicationEventNameEmpty {
            get {
                return ResourceManager.GetString("ApplicationEventNameEmpty", resourceCulture);
            }
        }
        
        internal static string DomainEventNameDuplicate {
            get {
                return ResourceManager.GetString("DomainEventNameDuplicate", resourceCulture);
            }
        }
        
        internal static string DomainEventTypeEmpty {
            get {
                return ResourceManager.GetString("DomainEventTypeEmpty", resourceCulture);
            }
        }
        
        internal static string ApplicationEventNameDuplicate {
            get {
                return ResourceManager.GetString("ApplicationEventNameDuplicate", resourceCulture);
            }
        }
        
        internal static string ApplicationEventTypeEmpty {
            get {
                return ResourceManager.GetString("ApplicationEventTypeEmpty", resourceCulture);
            }
        }
        
        internal static string CorrespondingRelationshipMissing {
            get {
                return ResourceManager.GetString("CorrespondingRelationshipMissing", resourceCulture);
            }
        }
        
        internal static string EntityKeyIsRequired {
            get {
                return ResourceManager.GetString("EntityKeyIsRequired", resourceCulture);
            }
        }
        
        internal static string DataConnectionInvalidFileUri {
            get {
                return ResourceManager.GetString("DataConnectionInvalidFileUri", resourceCulture);
            }
        }
        
        internal static string NuidKeyMissingProperty {
            get {
                return ResourceManager.GetString("NuidKeyMissingProperty", resourceCulture);
            }
        }
        
        internal static string EntityKeyShouldNotBeCompoundType {
            get {
                return ResourceManager.GetString("EntityKeyShouldNotBeCompoundType", resourceCulture);
            }
        }
        
        internal static string DuplicateItemInCollection {
            get {
                return ResourceManager.GetString("DuplicateItemInCollection", resourceCulture);
            }
        }
        
        internal static string EntityUniqueAttributeConstraintCanReferenceOnlyExistingAttributes {
            get {
                return ResourceManager.GetString("EntityUniqueAttributeConstraintCanReferenceOnlyExistingAttributes", resourceCulture);
            }
        }
        
        internal static string NameSameAsEnclosingType {
            get {
                return ResourceManager.GetString("NameSameAsEnclosingType", resourceCulture);
            }
        }
        
        internal static string EntityOwnedCannotBeAuditable {
            get {
                return ResourceManager.GetString("EntityOwnedCannotBeAuditable", resourceCulture);
            }
        }
        
        internal static string EntityKeysRequired {
            get {
                return ResourceManager.GetString("EntityKeysRequired", resourceCulture);
            }
        }
        
        internal static string OwnedEntityKeysMustBeNull {
            get {
                return ResourceManager.GetString("OwnedEntityKeysMustBeNull", resourceCulture);
            }
        }
        
        internal static string RelationEntityDependentMustHaveSingleKey {
            get {
                return ResourceManager.GetString("RelationEntityDependentMustHaveSingleKey", resourceCulture);
            }
        }
        
        internal static string EntityOwnedCannotBeRelatedToOtherEntities {
            get {
                return ResourceManager.GetString("EntityOwnedCannotBeRelatedToOtherEntities", resourceCulture);
            }
        }
        
        internal static string EntityOwnedCannotHaveRelationships {
            get {
                return ResourceManager.GetString("EntityOwnedCannotHaveRelationships", resourceCulture);
            }
        }
        
        internal static string IntegrationEventsServerAzureServiceBusConfigRequired {
            get {
                return ResourceManager.GetString("IntegrationEventsServerAzureServiceBusConfigRequired", resourceCulture);
            }
        }
        
        internal static string SolutionPlatformIdEmpty {
            get {
                return ResourceManager.GetString("SolutionPlatformIdEmpty", resourceCulture);
            }
        }
        
        internal static string SolutionVersionEmpty {
            get {
                return ResourceManager.GetString("SolutionVersionEmpty", resourceCulture);
            }
        }
        
        internal static string SolutionVersionPattern {
            get {
                return ResourceManager.GetString("SolutionVersionPattern", resourceCulture);
            }
        }
        
        internal static string IntegrationTransformationTypeEmpty {
            get {
                return ResourceManager.GetString("IntegrationTransformationTypeEmpty", resourceCulture);
            }
        }
        
        internal static string EntityCompoundKeyTextFieldsCantBeLocalized {
            get {
                return ResourceManager.GetString("EntityCompoundKeyTextFieldsCantBeLocalized", resourceCulture);
            }
        }
        
        internal static string EntityOwnedTextFieldsCantBeLocalized {
            get {
                return ResourceManager.GetString("EntityOwnedTextFieldsCantBeLocalized", resourceCulture);
            }
        }
        
        internal static string InfrastructureEndPointsDefaultsFalse {
            get {
                return ResourceManager.GetString("InfrastructureEndPointsDefaultsFalse", resourceCulture);
            }
        }
        
        internal static string SolutionDefaultsFalse {
            get {
                return ResourceManager.GetString("SolutionDefaultsFalse", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetDatabaseOptionsDefaultsFalse {
            get {
                return ResourceManager.GetString("IntegrationTargetDatabaseOptionsDefaultsFalse", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetDatabaseOptionsTableNameEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetDatabaseOptionsTableNameEmpty", resourceCulture);
            }
        }
        
        internal static string IntegrationTargetDatabaseOptionsSchemaEmpty {
            get {
                return ResourceManager.GetString("IntegrationTargetDatabaseOptionsSchemaEmpty", resourceCulture);
            }
        }
    }
}
