using System.Collections.Generic;

namespace Nox.Types;

public static class KnownColor
{
    public static Dictionary<string, System.Drawing.Color> Colors = new Dictionary<string, System.Drawing.Color>()
    {
        { "AliceBlue", System.Drawing.Color.AliceBlue },
        { "AntiqueWhite", System.Drawing.Color.AntiqueWhite },
        { "Aqua", System.Drawing.Color.Aqua },
        { "Aquamarine", System.Drawing.Color.Aquamarine },
        { "Azure", System.Drawing.Color.Azure },
        { "Beige", System.Drawing.Color.Beige },
        { "Bisque", System.Drawing.Color.Bisque },
        { "Black", System.Drawing.Color.Black },
        { "BlanchedAlmond", System.Drawing.Color.BlanchedAlmond },
        { "Blue", System.Drawing.Color.Blue },
        { "BlueViolet", System.Drawing.Color.BlueViolet },
        { "Brown", System.Drawing.Color.Brown },
        { "BurlyWood", System.Drawing.Color.BurlyWood },
        { "CadetBlue", System.Drawing.Color.CadetBlue },
        { "Chartreuse", System.Drawing.Color.Chartreuse },
        { "Chocolate", System.Drawing.Color.Chocolate },
        { "Coral", System.Drawing.Color.Coral },
        { "CornflowerBlue", System.Drawing.Color.CornflowerBlue },
        { "Cornsilk", System.Drawing.Color.Cornsilk },
        { "Crimson", System.Drawing.Color.Crimson },
        { "DarkBlue", System.Drawing.Color.DarkBlue },
        { "DarkCyan", System.Drawing.Color.DarkCyan },
        { "DarkGoldenrod", System.Drawing.Color.DarkGoldenrod },
        { "DarkGray", System.Drawing.Color.DarkGray },
        { "DarkGreen", System.Drawing.Color.DarkGreen },
        { "DarkKhaki", System.Drawing.Color.DarkKhaki },
        { "DarkMagenta", System.Drawing.Color.DarkMagenta },
        { "DarkOliveGreen", System.Drawing.Color.DarkOliveGreen },
        { "DarkOrange", System.Drawing.Color.DarkOrange },
        { "DarkOrchid", System.Drawing.Color.DarkOrchid },
        { "DarkRed", System.Drawing.Color.DarkRed },
        { "DarkSalmon", System.Drawing.Color.DarkSalmon },
        { "DarkSeaGreen", System.Drawing.Color.DarkSeaGreen },
        { "DarkSlateBlue", System.Drawing.Color.DarkSlateBlue },
        { "DarkSlateGray", System.Drawing.Color.DarkSlateGray },
        { "DarkTurquoise", System.Drawing.Color.DarkTurquoise },
        { "DarkViolet", System.Drawing.Color.DarkViolet },
        { "DeepPink", System.Drawing.Color.DeepPink },
        { "DeepSkyBlue", System.Drawing.Color.DeepSkyBlue },
        { "DimGray", System.Drawing.Color.DimGray },
        { "DodgerBlue", System.Drawing.Color.DodgerBlue },
        { "Firebrick", System.Drawing.Color.Firebrick },
        { "FloralWhite", System.Drawing.Color.FloralWhite },
        { "ForestGreen", System.Drawing.Color.ForestGreen },
        { "Gainsboro", System.Drawing.Color.Gainsboro },
        { "GhostWhite", System.Drawing.Color.GhostWhite },
        { "Gold", System.Drawing.Color.Gold },
        { "Goldenrod", System.Drawing.Color.Goldenrod },
        { "Gray", System.Drawing.Color.Gray },
        { "Green", System.Drawing.Color.Green },
        { "GreenYellow", System.Drawing.Color.GreenYellow },
        { "Honeydew", System.Drawing.Color.Honeydew },
        { "HotPink", System.Drawing.Color.HotPink },
        { "IndianRed", System.Drawing.Color.IndianRed },
        { "Indigo", System.Drawing.Color.Indigo },
        { "Ivory", System.Drawing.Color.Ivory },
        { "Khaki", System.Drawing.Color.Khaki },
        { "Lavender", System.Drawing.Color.Lavender },
        { "LavenderBlush", System.Drawing.Color.LavenderBlush },
        { "LawnGreen", System.Drawing.Color.LawnGreen },
        { "LemonChiffon", System.Drawing.Color.LemonChiffon },
        { "LightBlue", System.Drawing.Color.LightBlue },
        { "LightCoral", System.Drawing.Color.LightCoral },
        { "LightCyan", System.Drawing.Color.LightCyan },
        { "LightGoldenrodYellow", System.Drawing.Color.LightGoldenrodYellow },
        { "LightGray", System.Drawing.Color.LightGray },
        { "LightGreen", System.Drawing.Color.LightGreen },
        { "LightPink", System.Drawing.Color.LightPink },
        { "LightSalmon", System.Drawing.Color.LightSalmon },
        { "LightSeaGreen", System.Drawing.Color.LightSeaGreen },
        { "LightSkyBlue", System.Drawing.Color.LightSkyBlue },
        { "LightSlateGray", System.Drawing.Color.LightSlateGray },
        { "LightSteelBlue", System.Drawing.Color.LightSteelBlue },
        { "LightYellow", System.Drawing.Color.LightYellow },
        { "Lime", System.Drawing.Color.Lime },
        { "LimeGreen", System.Drawing.Color.LimeGreen },
        { "Linen", System.Drawing.Color.Linen },
        { "Magenta", System.Drawing.Color.Magenta },
        { "Maroon", System.Drawing.Color.Maroon },
        { "MediumAquamarine", System.Drawing.Color.MediumAquamarine },
        { "MediumBlue", System.Drawing.Color.MediumBlue },
        { "MediumOrchid", System.Drawing.Color.MediumOrchid },
        { "MediumPurple", System.Drawing.Color.MediumPurple },
        { "MediumSeaGreen", System.Drawing.Color.MediumSeaGreen },
        { "MediumSlateBlue", System.Drawing.Color.MediumSlateBlue },
        { "MediumSpringGreen", System.Drawing.Color.MediumSpringGreen },
        { "MediumTurquoise", System.Drawing.Color.MediumTurquoise },
        { "MediumVioletRed", System.Drawing.Color.MediumVioletRed },
        { "MidnightBlue", System.Drawing.Color.MidnightBlue },
        { "MintCream", System.Drawing.Color.MintCream },
        { "MistyRose", System.Drawing.Color.MistyRose },
        { "Moccasin", System.Drawing.Color.Moccasin },
        { "NavajoWhite", System.Drawing.Color.NavajoWhite },
        { "Navy", System.Drawing.Color.Navy },
        { "OldLace", System.Drawing.Color.OldLace },
        { "Olive", System.Drawing.Color.Olive },
        { "OliveDrab", System.Drawing.Color.OliveDrab },
        { "Orange", System.Drawing.Color.Orange },
        { "OrangeRed", System.Drawing.Color.OrangeRed },
        { "Orchid", System.Drawing.Color.Orchid },
        { "PaleGoldenrod", System.Drawing.Color.PaleGoldenrod },
        { "PaleGreen", System.Drawing.Color.PaleGreen },
        { "PaleTurquoise", System.Drawing.Color.PaleTurquoise },
        { "PaleVioletRed", System.Drawing.Color.PaleVioletRed },
        { "PapayaWhip", System.Drawing.Color.PapayaWhip },
        { "PeachPuff", System.Drawing.Color.PeachPuff },
        { "Peru", System.Drawing.Color.Peru },
        { "Pink", System.Drawing.Color.Pink },
        { "Plum", System.Drawing.Color.Plum },
        { "PowderBlue", System.Drawing.Color.PowderBlue },
        { "Purple", System.Drawing.Color.Purple },
        { "Red", System.Drawing.Color.Red },
        { "RosyBrown", System.Drawing.Color.RosyBrown },
        { "RoyalBlue", System.Drawing.Color.RoyalBlue },
        { "SaddleBrown", System.Drawing.Color.SaddleBrown },
        { "Salmon", System.Drawing.Color.Salmon },
        { "SandyBrown", System.Drawing.Color.SandyBrown },
        { "SeaGreen", System.Drawing.Color.SeaGreen },
        { "SeaShell", System.Drawing.Color.SeaShell },
        { "Sienna", System.Drawing.Color.Sienna },
        { "Silver", System.Drawing.Color.Silver },
        { "SkyBlue", System.Drawing.Color.SkyBlue },
        { "SlateBlue", System.Drawing.Color.SlateBlue },
        { "SlateGray", System.Drawing.Color.SlateGray },
        { "Snow", System.Drawing.Color.Snow },
        { "SpringGreen", System.Drawing.Color.SpringGreen },
        { "SteelBlue", System.Drawing.Color.SteelBlue },
        { "Tan", System.Drawing.Color.Tan },
        { "Teal", System.Drawing.Color.Teal },
        { "Thistle", System.Drawing.Color.Thistle },
        { "Tomato", System.Drawing.Color.Tomato },
        { "Turquoise", System.Drawing.Color.Turquoise },
        { "Violet", System.Drawing.Color.Violet },
        { "Wheat", System.Drawing.Color.Wheat },
        { "White", System.Drawing.Color.White },
        { "WhiteSmoke", System.Drawing.Color.WhiteSmoke },
        { "Yellow", System.Drawing.Color.Yellow },
        { "YellowGreen", System.Drawing.Color.YellowGreen },
    };

    public static bool TryGetNamedColor(string text,  out System.Drawing.Color color)
    {
        color = System.Drawing.Color.Empty;

        foreach (var c in Colors.Values)
        {
            if (c.Name == text)
            {
                color = c;
                return true;
            }
        }

        return false;
    }
}
