name: Publish Schemas

on:
  workflow_dispatch:
  release:
    types: [released]
  workflow_run:
    workflows: [Scheduled release]
    types:
      - completed

jobs:
  schemas-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./schemas/
          #dangerous-clean-slate: true
